
name: Clarence
# 描述/签名
description: 编程随想


# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: https://namedhard.github.io/ps-static-source/img/ico1-1.jpg

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://namedhard.github.io/ps-static-source/img/ico1-1.jpg


# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags

# 每页的文章数
paginate: 8

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  email: zhuxian0793@gmail.com 
  github: NamedHard
  rss: #随便填点啥RSS就能用了
  # stackoverflow: # http://stackoverflow.com/<>
  # tumblr: # https://<username>.tumblr.com
  # twitter: # https://www.twitter.com/<your_twitter_username> 
  # youtube: # channel/<your_long_string> or user/<user-name>

# 站点页脚的文字
footer-text: Try it hard, work it easy

# 输入Google Analytics web tracking code
google_analytics:

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
# baseurl: 

# Gitalk settings
comments: 
  gitalk: true
  gitalk_clientID: 'fa7cdd0c8642eff1bb43'
  gitalk_Secret: '1018d0a03ac13cdc18b483d4252586fb8e1f51a2'
  gitalk_repo: 'namedhard.github.io'
  gitalk_owner: 'namedhard'
  gitalk_admin: 'namedhard'
  distractionFreeMode: true

#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

excerpt_separator: ---
